# Copyright (c) 2017-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2017-present Sven Greb <code@svengreb.de>

# Project:    Nord Alacritty
# Version:    0.1.0
# Repository: https://github.com/arcticicestudio/nord-alacritty
# License:    MIT
# References:
#   https://github.com/alacritty/alacritty

[env]
# This value is used to set the `$TERM` environment variable for
# each instance of Alacritty. If it is not present, alacritty will
# check the local terminfo database and use `alacritty` if it is
# available, otherwise `xterm-256color` is used.
TERM = "xterm-256color"

[window]
# Spread additional padding evenly around the terminal content.
[window.padding]
x = 10
y = 10

# Remove buttons
# Open in full screen
# startup_mode = "SimpleFullscreen"

[font]
  [font.normal]
  family = "JetBrains Mono"
  style = "Regular"
  
  [font.bold]
  family = "JetBrains Mono"
  style = "Bold"
  
  [font.italic]
  family = "JetBrains Mono"
  style = "Italic"
  
[colors]
  [colors.primary]
  background = "#2e3440"
  foreground = "#d8dee9"
  dim_foreground = "#a5abb6"

  [colors.cursor]
  text = "#2e3440"
  cursor = "#d8dee9"

  [colors.vi_mode_cursor]
  text = "#2e3440"
  cursor = "#d8dee9"

  [colors.selection]
  text = "CellForeground"
  background = "#4c566a"

  [colors.search]
  [colors.search.matches]
  foreground = "CellBackground"
  background = "#88c0d0"
  

  [colors.normal]
  black = "#3b4252"
  red = "#bf616a"
  green = "#a3be8c"
  yellow = "#ebcb8b"
  blue = "#81a1c1"
  magenta = "#b48ead"
  cyan = "#88c0d0"
  white = "#e5e9f0"

  [colors.bright]
  black = "#4c566a"
  red = "#bf616a"
  green = "#a3be8c"
  yellow = "#ebcb8b"
  blue = "#81a1c1"
  magenta = "#b48ead"
  cyan = "#8fbcbb"
  white = "#eceff4"

  [colors.dim]
  black = "#373e4d"
  red = "#94545d"
  green = "#809575"
  yellow = "#b29e75"
  blue = "#68809a"
  magenta = "#8c738c"
  cyan = "#6d96a5"
  white = "#aeb3bb"

